# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: cargo
'on':
  push:
  pull_request:
concurrency:
  group: cargo-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test -vv
      - run: target/debug/reo --help
      - run: cargo fmt --check
