name: cargo
on:
  push:
  pull_request:
concurrency:
  group: cargo-${{ github.ref }}
  cancel-in-progress: true
jobs:
  cargo:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test -vv
      - run: target/debug/reo --help
      - run: cargo fmt --check
